run-dev:
	yarn start:dev

test:
	yarn test

local-build:
	docker compose -f ./.docker/local/docker-compose.yml build

local-up:
	docker compose -f ./.docker/local/docker-compose.yml up -d

local-down:
	docker compose -f ./.docker/local/docker-compose.yml down

local-drop:
	docker compose -f ./.docker/local/docker-compose.yml rm -fsv
